DEFAULT_TARGET_DEVICE_IP = "localhost"
DEFAULT_STREAMING_PORT = "5001"
DEFAULT_COMMUNICATION_PORT = "5002"

DEFAULT_FPV_URL = "192.168.31.144"
DEFAULT_FPV_USR = "hellojanaka"
DEFAULT_FPV_PW = "testing1234"
DEFAULT_TPV_URL= "0"
DEFAULT_BROWSER_URL = "figma.com"
DEFAULT_VIDEO_DEVICE_IDX = 0
DEFAULT_AUDIO_DEVICE_1_IDX = 0
DEFAULT_AUDIO_DEVICE_2_IDX = 1

DEFAULT_CONNECTION_TIMEOUT = 30